### PR TITLE
Update for 1.0.11

### PR DESCRIPTION
**Pull request by lAzrythl**
don't mind my 100 includes, just using my shitty mod template lol

P.S. sorry for all the PRs i have no idea how to do multiple changes in one pr

### CODE REVIEW

**Comment by RedBrumbler** [comment]
You've removed functionality, thus I am not accepting this

**Comment by lAzrythl** [comment]
> You've removed functionality, thus I am not accepting this

eh okay, works fine tho

**Comment by RedBrumbler** [comment]
There was functionality to not break map loader gravity which you've removed making the mod incompatible with map loader

**Comment by lAzrythl** [comment]
oh lol had no idea about that, i'll revise

**Comment by RedBrumbler** [comment]
Also if you just pr after doing an amount of commits its just gonna be a single pr

**Comment by lAzrythl** [comment]
ah ok

**Pull request closed without merging**
