### PR TITLE
Added button enabling

### PR DESCRIPTION
**Pull request by Waulta**
- Press and hold the A button on your right controller to enable
- When you release the A button, the mod disables
- Whenever you touch a surface, you will fall towards that surface
- Auto Disables in public lobbies
- Works in private lobbies

### CODE REVIEW

**Comment by eeeeeeeeeeeeeee405** [comment]
hey can i get the mod?

**Comment by Boopmonke** [comment]
Can I get this please

**Comment by eeeeeeeeeeeeeee405** [comment]
What? I'd like the mod please

**Comment by Boopmonke** [comment]
> Ok I'll msg u there thanks🙏

Bet

**Comment by eeeeeeeeeeeeeee405** [comment]
I added u I'm memermanz

**Comment by Boopmonke** [comment]
> I added u I'm memermanz

whats your tag?

**Comment by eeeeeeeeeeeeeee405** [comment]
MemerManz#9449

**Pull request closed without merging**
